const sceneNames={airport:'機場',hotel:'飯店',cafe:'咖啡廳',yakiniku:'燒肉餐廳',laundry:'洗衣店',stationery:'文具店',school:'學校',office:'公司',hospital:'醫院',pharmacy:'藥妝店',train:'電車',supermarket:'超市',postoffice:'郵局',hairSalon:'髮廊',bank:'銀行',gym:'健身房',apartment:'租屋',cityHall:'市役所'};
const levelOrder=['N5','N4','N3','N2','N1'];
const data={
airport:{N5:['トイレはどこですか。','廁所在哪裡？'],N4:['荷物がまだ出てきません。','我的行李還沒有出來。'],N3:['乗り継ぎの手続きはどこでできますか。','轉機手續在哪裡辦？'],N2:['別の便に変更していただくことは可能でしょうか。','是否可以幫我改成其他班機？'],N1:['恐れ入りますが、状況をご確認のうえ、ご案内いただけますでしょうか。','不好意思，能否請您確認狀況後為我說明？']},
hotel:{N5:['予約があります。','我有預約。'],N4:['朝食は何時からですか。','早餐從幾點開始？'],N3:['部屋のエアコンがつかないようです。','房間的冷氣好像打不開。'],N2:['可能であれば、チェックアウトを一時間延ばしていただけますか。','如果可以的話，能幫我延後一小時退房嗎？'],N1:['差し支えなければ、上層階の静かな部屋をご用意いただけますでしょうか。','若方便的話，能否為我安排高樓層且安靜的房間？']},
cafe:{N5:['コーヒーをください。','請給我咖啡。'],N4:['持ち帰りでお願いします。','我要外帶。'],N3:['砂糖を少なめにできますか。','糖可以少一點嗎？'],N2:['甘さを控えめにしていただけると助かります。','若能幫我甜度低一點就太好了。'],N1:['酸味が強すぎないものを選びたいのですが、おすすめはありますでしょうか。','我想選酸味不要太強的，有推薦的嗎？']},
yakiniku:{N5:['二人です。','兩位。'],N4:['予約しています。','我有預約。'],N3:['おすすめの部位はどれですか。','推薦的部位是哪一種？'],N2:['焼き加減は店員さんにお任せしてもいいですか。','烤的程度可以交給店員決定嗎？'],N1:['脂が控えめで食べやすい部位を中心にお願いできますでしょうか。','能否以油脂較少、比較好入口的部位為主？']},
laundry:{N5:['洗濯機はどれですか。','洗衣機是哪一台？'],N4:['乾燥機は何分かかりますか。','烘乾機需要幾分鐘？'],N3:['両替機が使えないようです。','兌幣機好像不能用。'],N2:['洗濯が終わったら、すぐ取りに来たほうがいいですか。','洗完後最好馬上來拿嗎？'],N1:['衣類が傷まないように、低温で乾燥させることは可能でしょうか。','能否用低溫烘乾，以免衣物受損？']},
stationery:{N5:['ノートはどこですか。','筆記本在哪裡？'],N4:['このペンを試してもいいですか。','可以試寫這支筆嗎？'],N3:['同じ色で細いタイプはありますか。','有同色但比較細的款式嗎？'],N2:['プレゼント用に包んでいただけますか。','可以幫我包成禮物嗎？'],N1:['書き心地が軽く、長時間使っても疲れにくいものを探しています。','我在找書寫感輕、長時間使用也不容易累的筆。']},
school:{N5:['宿題があります。','有作業。'],N4:['今日は休んでもいいですか。','今天可以請假嗎？'],N3:['提出期限を一日延ばしていただけますか。','可以把繳交期限延後一天嗎？'],N2:['発表の順番を変更していただくことは可能ですか。','可以更改報告順序嗎？'],N1:['準備不足で恐縮ですが、発表時間を調整していただけますでしょうか。','準備不足很不好意思，能否調整我的報告時間？']},
office:{N5:['会議は何時ですか。','會議是幾點？'],N4:['資料を送ってください。','請把資料寄給我。'],N3:['進捗を確認してもいいですか。','可以確認一下進度嗎？'],N2:['締め切りを少し延ばしていただけると助かります。','若能稍微延後截止日就太好了。'],N1:['認識に相違がないか、念のため確認させていただけますでしょうか。','為避免認知有落差，能否讓我再次確認？']},
hospital:{N5:['頭が痛いです。','我頭痛。'],N4:['熱があります。','我發燒。'],N3:['昨日から喉が痛くて、咳も出ます。','從昨天開始喉嚨痛，也會咳嗽。'],N2:['薬を飲むタイミングを教えていただけますか。','可以告訴我吃藥的時間點嗎？'],N1:['以前同じ薬で副作用が出たことがあるのですが、問題ないでしょうか。','以前吃同樣的藥曾有副作用，這樣沒問題嗎？']},
pharmacy:{N5:['風邪薬はありますか。','有感冒藥嗎？'],N4:['眠くならない薬がほしいです。','我想要不會想睡的藥。'],N3:['この薬は食後に飲むんですか。','這個藥是飯後吃嗎？'],N2:['アレルギーがあるので、成分を確認してもいいですか。','我有過敏，可以確認成分嗎？'],N1:['症状に合うものを選びたいので、薬剤師の方に相談できますでしょうか。','我想選適合症狀的藥，能否諮詢藥師？']},
train:{N5:['駅はどこですか。','車站在哪裡？'],N4:['この電車は新宿に行きますか。','這班電車會到新宿嗎？'],N3:['乗り換えはどの駅ですればいいですか。','要在哪一站換車？'],N2:['遅延証明書はどこでもらえますか。','延誤證明在哪裡可以拿？'],N1:['運転見合わせの場合、振替輸送を利用することは可能でしょうか。','若停駛，是否可以使用替代運輸？']},
supermarket:{N5:['袋をください。','請給我袋子。'],N4:['これはいくらですか。','這個多少錢？'],N3:['温めてもらえますか。','可以幫我加熱嗎？'],N2:['賞味期限が長いものはありますか。','有保存期限比較長的嗎？'],N1:['できれば添加物が少ない商品を選びたいのですが。','如果可以，我想選添加物較少的商品。']},
postoffice:{N5:['これを送りたいです。','我想寄這個。'],N4:['台湾までいくらですか。','寄到台灣多少錢？'],N3:['追跡番号はありますか。','有追蹤號碼嗎？'],N2:['壊れやすいものなので、丁寧に扱っていただけますか。','因為是易碎品，可以請您小心處理嗎？'],N1:['到着予定日と補償の有無を確認させていただけますでしょうか。','能否讓我確認預計到達日與是否有補償？']},
hairSalon:{N5:['少し切ってください。','請剪一點點。'],N4:['前髪は短くしないでください。','瀏海請不要剪短。'],N3:['写真のような感じにできますか。','可以剪成像照片這樣嗎？'],N2:['自然にまとまるように整えていただけますか。','可以幫我修成自然好整理的樣子嗎？'],N1:['長さはあまり変えずに、全体の重さだけ調整していただけますでしょうか。','能否不要太改變長度，只調整整體厚重感？']},
bank:{N5:['お金を下ろしたいです。','我想提款。'],N4:['両替できますか。','可以換錢嗎？'],N3:['手数料はいくらかかりますか。','手續費是多少？'],N2:['海外送金の手続きについて教えてください。','請告訴我海外匯款的手續。'],N1:['必要書類と本人確認の流れを事前に確認させていただけますでしょうか。','能否讓我事先確認所需文件與身分確認流程？']},
gym:{N5:['見学できますか。','可以參觀嗎？'],N4:['一日だけ使えますか。','可以只使用一天嗎？'],N3:['初心者向けのクラスはありますか。','有適合初學者的課嗎？'],N2:['入会する前に料金プランを比較したいです。','入會前我想比較費用方案。'],N1:['無理なく続けられる頻度で、効果的なメニューを相談したいです。','我想諮詢能持續且有效的訓練菜單。']},
apartment:{N5:['部屋を見たいです。','我想看房。'],N4:['駅から近いですか。','離車站近嗎？'],N3:['初期費用はいくらぐらいですか。','初期費用大概多少？'],N2:['契約前に設備の状態を確認してもいいですか。','簽約前可以確認設備狀態嗎？'],N1:['退去時の費用負担について、事前に詳しく確認させていただけますでしょうか。','能否事先詳細確認退租時的費用負擔？']},
cityHall:{N5:['住民票がほしいです。','我想要住民票。'],N4:['この書類はどこに出しますか。','這份文件要交到哪裡？'],N3:['受付番号を取ればいいですか。','拿號碼牌就可以嗎？'],N2:['必要な本人確認書類を教えていただけますか。','可以告訴我需要哪些身分確認文件嗎？'],N1:['手続きに不備がないか、提出前に確認していただけますでしょうか。','提交前能否幫我確認手續是否有缺漏？']}
};
const particles=[['N5','私は台湾人です。','は','主題標記：我這個人，是台灣人。',['は','が','を','で']],['N5','水をください。','を','動作的對象：要的是水。',['は','が','を','に']],['N5','駅に行きます。','に','到達點：去車站。',['に','で','を','と']],['N4','駅で友だちに会いました。','で','動作發生的場所：在車站見面。',['で','に','へ','を']],['N4','友だちと映画を見ます。','と','一起做動作的對象：和朋友。',['と','も','が','は']],['N3','雨が降りそうです。','が','描述眼前現象或主語：雨好像要下。',['が','は','を','で']],['N3','日本へ旅行に行きます。','へ','方向感：往日本去。',['へ','で','を','と']],['N2','この件について確認します。','について','關於某件事進行確認。',['について','によって','として','に対して']],['N1','努力なくして成功はない。','なくして','沒有前項就不可能有後項。',['なくして','として','にして','をもって']]];
const kana={'忘れない':'わすれない','忘れて':'わすれて','忘れる':'わすれる','忘れ':'わすれ','忘':'わす','私':'わたし','僕':'ぼく','君':'きみ','誰':'だれ','何':'なに','今':'いま','今日':'きょう','明日':'あした','昨日':'きのう','世界':'せかい','時間':'じかん','未来':'みらい','過去':'かこ','心':'こころ','夢':'ゆめ','愛':'あい','恋':'こい','涙':'なみだ','声':'こえ','歌':'うた','空':'そら','星':'ほし','月':'つき','夜':'よる','朝':'あさ','風':'かぜ','雨':'あめ','花':'はな','道':'みち','街':'まち','光':'ひかり','影':'かげ','笑顔':'えがお','言葉':'ことば','約束':'やくそく','季節':'きせつ','思い出':'おもいで','一人':'ひとり','二人':'ふたり','歩く':'あるく','走る':'はしる','泣く':'なく','笑う':'わらう','会う':'あう','行く':'いく','帰る':'かえる','見える':'みえる','聞こえる':'きこえる','探して':'さがして','抱きしめ':'だきしめ','輝く':'かがやく'};
const $=s=>document.querySelector(s),SR=window.SpeechRecognition||window.webkitSpeechRecognition;
const state={mode:'quiz',level:'N5',scene:'airport',queue:[],index:0,current:null,answered:false,stats:load('jpStatsV5',{date:today(),total:0,correct:0}),weak:load('jpWeakV5',{})};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}function save(){localStorage.setItem('jpStatsV5',JSON.stringify(state.stats));localStorage.setItem('jpWeakV5',JSON.stringify(state.weak))}function today(){return new Date().toISOString().slice(0,10)}function norm(){if(state.stats.date!==today()){state.stats={date:today(),total:0,correct:0}}}function shuffle(a){return a.map(v=>({v,r:Math.random()})).sort((x,y)=>x.r-y.r).map(x=>x.v)}
function setMode(m){state.mode=m;document.querySelectorAll('.mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#setupPanel').classList.toggle('hidden',m==='lyrics');$('#quizPanel').classList.add('hidden');$('#lyricsPanel').classList.toggle('hidden',m!=='lyrics')}
function startQuiz(){state.queue=state.mode==='particles'?particleQuestions():sceneQuestions();state.index=0;$('#setupPanel').classList.add('hidden');$('#quizPanel').classList.remove('hidden');renderQuestion()}
function particleQuestions(){return shuffle(particles.filter(p=>p[0]===state.level).map(p=>({type:'particle',level:p[0],prompt:p[1].replace(p[2],'（　）'),sentence:p[1],answer:p[2],note:p[3],choices:p[4],speakText:p[1],id:p[0]+p[1]})))}
function sceneQuestions(){const row=data[state.scene][state.level],jp=row[0],zh=row[1],same=Object.values(data[state.scene]).filter(x=>x!==row),all=Object.values(data).map(s=>s[state.level]).filter(x=>x&&x!==row);const zhD=[...same.map(x=>x[1]),...shuffle(all).map(x=>x[1])],jpD=[...same.map(x=>x[0]),...shuffle(all).map(x=>x[0])];return shuffle([{type:'jpToZh',prompt:jp,answer:zh,speakText:jp,choices:choices(zh,zhD),title:'日文選中文',hint:'看日文或聽發音，選出正確中文。'},{type:'zhToJp',prompt:zh,answer:jp,speakText:jp,choices:choices(jp,jpD),title:'中文選日文',hint:'看中文，選出最自然的日文。'},{type:'audioToZh',prompt:'聽發音，選出正確意思。',answer:zh,speakText:jp,choices:choices(zh,zhD),title:'聽音選意思',hint:'先按播放，只靠聽力選中文。'}].map((q,i)=>({...q,id:state.level+state.scene+i,level:state.level,scene:state.scene})))}
function choices(ans,ds){return shuffle([ans,...ds.filter(Boolean).filter(x=>x!==ans)]).slice(0,4)}
function renderQuestion(){const q=state.current=state.queue[state.index%state.queue.length];state.answered=false;$('#quizMeta').textContent=q.type==='particle'?`${q.level} · 助詞`:`${q.level} · ${sceneNames[q.scene]}`;$('#quizTitle').textContent=q.type==='particle'?'助詞填空':q.title;$('#stepBadge').textContent=`${state.index+1} / ${state.queue.length}`;$('#questionPrompt').textContent=q.type==='particle'?'選出空格裡最自然的助詞。':q.hint;$('#questionText').textContent=q.prompt;$('#answerReveal').classList.add('hidden');$('#answerReveal').textContent='';$('#feedback').textContent=q.type==='particle'?'選一個助詞。':'先作答；需要時可以播放或慢速聽。';$('#speechResult').textContent='';const box=$('#answers');box.innerHTML='';shuffle(q.choices).forEach(c=>{const b=document.createElement('button');b.type='button';b.textContent=c;b.onclick=()=>answer(c,b);box.appendChild(b)});renderStats();renderWeak()}
function answer(c,b){if(state.answered)return;state.answered=true;norm();state.stats.total++;const q=state.current,ok=c===q.answer;if(ok){state.stats.correct++;b.classList.add('correct');$('#feedback').textContent=q.type==='particle'?`答對。${q.note}`:'答對了。可以再跟讀一次。'}else{b.classList.add('wrong');markWeak(false);$('#feedback').textContent=q.type==='particle'?`正解：${q.answer}。${q.note}`:`正解：${q.answer}`}[...$('#answers').children].forEach(x=>{if(x.textContent===q.answer)x.classList.add('correct')});$('#answerReveal').textContent=q.type==='particle'?q.sentence:q.speakText;$('#answerReveal').classList.remove('hidden');save();renderStats();renderWeak()}
function play(rate){const q=state.current;if(!q||!speechSynthesis)return;if(q.type==='zhToJp'&&!state.answered){$('#feedback').textContent='中文選日文題要先作答，答完再播放正解。';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.speakText);u.lang='ja-JP';u.rate=rate;speechSynthesis.speak(u)}
function speakPractice(){const q=state.current;if(!q)return;if(!SR){$('#speechResult').textContent='這個瀏覽器不支援語音辨識；可以先用播放和慢速跟讀。';markWeak(false);return}const r=new SR();r.lang='ja-JP';r.interimResults=false;r.maxAlternatives=1;$('#feedback').textContent='開始聽你跟讀。';r.onresult=e=>{$('#speechResult').textContent=`辨識結果：${e.results[0][0].transcript}`};r.onerror=()=>{$('#speechResult').textContent='語音辨識沒有啟動。iPhone 通常需要 HTTPS 和麥克風權限。'};r.start()}
function markWeak(show=true){const q=state.current;if(!q)return;state.weak[q.id]={...q,missedAt:Date.now()};save();if(show)$('#feedback').textContent='已加入弱點。';renderWeak()}function nextQuestion(){state.index++;if(state.index>=state.queue.length){$('#setupPanel').classList.remove('hidden');$('#quizPanel').classList.add('hidden');return}renderQuestion()}
function convertLyrics(){const input=$('#lyricsInput').value.trim();if(!input){$('#lyricsOutput').innerHTML='<p>先放入授權來源的歌詞文字，或用上方歌名搜尋找到合法歌詞頁。</p>';return}let out=input.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));Object.entries(kana).sort((a,b)=>b[0].length-a[0].length).forEach(([k,v])=>{out=out.replace(new RegExp(k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'),`<ruby>${k}<rt>${v}</rt></ruby>`)});$('#lyricsOutput').innerHTML=out.split(/\n/).map(l=>`<p>${l||'&nbsp;'}</p>`).join('')}
function searchLyricsByTitle(){const t=$('#songTitleInput').value.trim();if(!t){$('#lyricsOutput').innerHTML='<p>先輸入歌名或歌手。</p>';return}const q=encodeURIComponent(`${t} 歌詞 公式 lyrics`);$('#searchLinks').classList.remove('hidden');$('#searchLinks').innerHTML=`<a target="_blank" rel="noopener noreferrer" href="https://www.google.com/search?q=${q}">Google 搜尋官方歌詞</a><a target="_blank" rel="noopener noreferrer" href="https://music.youtube.com/search?q=${encodeURIComponent(t)}">YouTube Music 搜尋</a><a target="_blank" rel="noopener noreferrer" href="https://music.apple.com/search?term=${encodeURIComponent(t)}">Apple Music 搜尋</a>`;$('#lyricsOutput').innerHTML='<p>已產生搜尋入口。找到官方或授權歌詞後，可以用授權 API 自動匯入；目前前端版不會爬取整首版權歌詞。</p>'}
function renderStats(){norm();$('#todayCount').textContent=state.stats.total;$('#accuracy').textContent=state.stats.total?`${Math.round(state.stats.correct/state.stats.total*100)}%`:'--';$('#weakCount').textContent=Object.keys(state.weak).length}function renderWeak(){const list=$('#weakList'),items=Object.values(state.weak).sort((a,b)=>b.missedAt-a.missedAt);list.innerHTML='';if(!items.length){const li=document.createElement('li');li.textContent='目前沒有弱點。';list.appendChild(li);return}items.slice(0,8).forEach(q=>{const li=document.createElement('li');li.innerHTML=`<strong>${q.level} ${q.type==='particle'?'助詞':sceneNames[q.scene]}</strong><br>${q.speakText}`;li.onclick=()=>{state.current=q;play(.82)};list.appendChild(li)})}
document.querySelector('.mode-tabs').onclick=e=>{const b=e.target.closest('button[data-mode]');if(b)setMode(b.dataset.mode)};$('#levelTabs').onclick=e=>{const b=e.target.closest('button[data-level]');if(!b)return;state.level=b.dataset.level;document.querySelectorAll('#levelTabs button').forEach(x=>x.classList.toggle('active',x===b))};$('#sceneSelect').onchange=e=>state.scene=e.target.value;$('#startQuiz').onclick=startQuiz;$('#homeButton').onclick=()=>{$('#setupPanel').classList.remove('hidden');$('#quizPanel').classList.add('hidden');$('#lyricsPanel').classList.toggle('hidden',state.mode!=='lyrics')};$('#playNormal').onclick=()=>play(.92);$('#playSlow').onclick=()=>play(.62);$('#speakTry').onclick=speakPractice;$('#markHard').onclick=()=>markWeak(true);$('#nextQuestion').onclick=nextQuestion;$('#clearWeak').onclick=()=>{state.weak={};save();renderWeak();renderStats()};$('#searchLyrics').onclick=searchLyricsByTitle;$('#convertLyrics').onclick=convertLyrics;$('#clearSong').onclick=()=>{$('#songTitleInput').value='';$('#lyricsInput').value='';$('#searchLinks').classList.add('hidden');$('#searchLinks').innerHTML='';$('#lyricsOutput').innerHTML='<p>搜尋結果或轉換後的假名會顯示在這裡。</p>'};if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js');norm();renderStats();renderWeak();
